import * as Joi from 'joi';

export const validationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'test', 'production').default('development'),
  PORT: Joi.number().default(4000),
  APP_NAME: Joi.string().default('FitNova AI'),
  APP_ORIGIN: Joi.string().min(1).default('http://localhost:3000,http://localhost:5173'),
  APP_TRUST_PROXY: Joi.boolean().truthy('true').falsy('false').default(false),
  SWAGGER_ENABLED: Joi.boolean().truthy('true').falsy('false').default(true),
  CORS_ALLOW_LOCALHOST: Joi.boolean().truthy('true').falsy('false').default(true),
  MONGODB_URI: Joi.string().required(),
  JWT_ACCESS_SECRET: Joi.string().min(16).required(),
  JWT_ACCESS_TTL: Joi.string().required(),
  JWT_REFRESH_SECRET: Joi.string().min(16).required(),
  JWT_REFRESH_TTL: Joi.string().required(),
  BCRYPT_SALT_ROUNDS: Joi.number().min(10).default(12),
  EMAIL_VERIFICATION_OTP_TTL_MINUTES: Joi.number().min(1).max(60).default(10),
  SMTP_HOST: Joi.string().hostname().default('smtp.gmail.com'),
  SMTP_PORT: Joi.number().port().default(465),
  SMTP_SECURE: Joi.boolean().truthy('true').falsy('false').default(true),
  SMTP_USER: Joi.string().allow('', null),
  SMTP_PASS: Joi.string().allow('', null),
  EMAIL_FROM: Joi.string().allow('', null),
  AI_PROVIDER: Joi.string().valid('gemini', 'openai').default('gemini'),
  GEMINI_API_KEY: Joi.string().allow('', null),
  GEMINI_MODEL: Joi.string().default('gemini-2.5-flash'),
  OPENAI_API_KEY: Joi.string().allow('', null),
  OPENAI_MODEL: Joi.string().default('gpt-4.1-mini'),
  REDIS_ENABLED: Joi.boolean().truthy('true').falsy('false').default(false),
  REDIS_HOST: Joi.string().hostname().default('127.0.0.1'),
  REDIS_PORT: Joi.number().port().default(6379),
  REDIS_USERNAME: Joi.string().allow('', null),
  REDIS_PASSWORD: Joi.string().allow('', null),
  REDIS_DB: Joi.number().min(0).default(0),
  STRIPE_SECRET_KEY: Joi.string().allow('', null),
  STRIPE_WEBHOOK_SECRET: Joi.string().allow('', null),
  STRIPE_PRICE_MONTHLY: Joi.string().allow('', null),
  STRIPE_PRICE_YEARLY: Joi.string().allow('', null),
  POSTGRES_URL: Joi.string().allow('', null),
  GLOBAL_RATE_LIMIT_TTL: Joi.number().min(1000).default(60000),
  GLOBAL_RATE_LIMIT: Joi.number().min(1).default(100),
  AI_RATE_LIMIT_TTL: Joi.number().min(1000).default(60000),
  AI_RATE_LIMIT: Joi.number().min(1).default(12),
  LOG_LEVEL: Joi.string().valid('error', 'warn', 'info', 'debug', 'verbose').default('debug'),
  LOG_TO_FILES: Joi.boolean().truthy('true').falsy('false').default(false),
});
